[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build:api"

[deploy]
startCommand = "cd apps/api && npx prisma migrate deploy && node dist/index.js"
healthcheckPath = "/api/hello"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
