[build]
builder = "NIXPACKS"
buildCommand = "npm run build:api"

[watch]
patterns = ["/apps/api/**"]

[deploy]
startCommand = "cd apps/api && npx prisma migrate deploy && node dist/apps/api/src/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
